"use client";

import { useEffect, useState } from "react";
import { PButton } from "@porsche-design-system/components-react/ssr";
import { api, SystemLogEvent } from "@/lib/api";

const categories = ["security", "access", "api", "health", "runtime"] as const;
const severities = ["info", "warning", "error"] as const;

export function SystemLogsPanel() {
  const [events, setEvents] = useState<SystemLogEvent[]>([]);
  const [category, setCategory] = useState(""); const [severity, setSeverity] = useState(""); const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const query = new URLSearchParams({ limit: "100", ...(category ? { category } : {}), ...(severity ? { severity } : {}), ...(search.trim() ? { search: search.trim() } : {}) }); setEvents(await api<SystemLogEvent[]>(`/admin/system-logs?${query}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load system logs."); } finally { setLoading(false); } }
  useEffect(() => { let active = true; void api<SystemLogEvent[]>("/admin/system-logs?limit=100").then((result) => { if (active) setEvents(result); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Unable to load system logs."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  return <section className="content-card system-logs-card"><div className="section-heading"><div><p className="eyebrow">Administration</p><h2>System logs</h2></div><div className="table-actions"><span className="status-dot">Sanitized events</span><PButton variant="secondary" onClick={() => void load()} disabled={loading}>{loading ? "Refreshing…" : "Refresh"}</PButton></div></div><p className="manager-note">Security, access, API, health, and runtime events. Secrets, tokens, passwords, cookies, and connection strings are never stored here.</p><div className="log-filters"><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">All categories</option>{categories.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>Severity<select value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="">All severities</option>{severities.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label className="log-search">Search<input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void load(); }} placeholder="Message, path, or request ID" /></label><PButton variant="secondary" onClick={() => void load()} disabled={loading}>Apply</PButton></div>{error ? <p role="alert" className="manager-note">{error}</p> : events.length ? <div className="table-wrap"><table className="data-table system-logs-table"><caption className="sr-only">System log events</caption><thead><tr><th scope="col">When</th><th scope="col">Level</th><th scope="col">Category</th><th scope="col">Event</th><th scope="col">Context</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td><time dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString()}</time></td><td><span className={`log-level ${event.severity}`}>{event.severity}</span></td><td><span className="event-badge">{event.category}</span></td><td><strong>{event.message}</strong>{event.actor && <small>{event.actor.name || event.actor.email}</small>}</td><td><small>{event.statusCode ? `${event.statusCode} · ` : ""}{event.path || event.requestId || "—"}</small></td></tr>)}</tbody></table></div> : <p className="manager-note">{loading ? "Loading events…" : "No events match these filters yet."}</p>}</section>;
}
