"use client";
/* These effects intentionally synchronize remote B2B resources after mount or selection changes. */
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { B2bShell, B2bState, formatB2bMoney } from "@/components/b2b/b2b-shell";
import type { B2bOrder, Company, CompanyRole, CustomerGroup, Membership, PriceList, Variant } from "@/components/b2b/types";
import { useTranslation } from "@/i18n/language-provider";

type Section = "companies" | "variants" | "groups" | "lists" | "orders";
const roleOptions: CompanyRole[] = ["OWNER", "ADMIN", "BUYER", "VIEWER"];

function ErrorNotice({ error }: { error: string }) { return error ? <p className="notice error" role="alert">{error}</p> : null; }
function SuccessNotice({ message }: { message: string }) { return message ? <p className="notice success" role="status">{message}</p> : null; }
function Badge({ value }: { value: string }) { return <span className={`b2b-badge ${value.toLowerCase()}`}>{value}</span>; }

export function B2bManagementPage({ section }: { section: Section }) {
  const titles = { companies: "Companies", variants: "Variants", groups: "Customer groups", lists: "Price lists", orders: "B2B orders" } as const;
  return <B2bShell title={titles[section]} active={section === "groups" ? "groups" : section === "lists" ? "lists" : section === "orders" ? "orders" : section}><section className="b2b-overview-section"><div className="b2b-stat-grid"><div className="metric-card"><span>{titles[section]}</span><strong><SectionCount section={section} /></strong></div><div className="metric-card"><span>Phase 2 status</span><strong className="b2b-status-text">Active</strong></div></div>{section === "companies" && <CompaniesPanel />}{section === "variants" && <VariantsPanel />}{section === "groups" && <GroupsPanel />}{section === "lists" && <PriceListsPanel />}{section === "orders" && <OrdersPanel />}</section></B2bShell>;
}

function SectionCount({ section }: { section: Section }) {
  const [count, setCount] = useState("—");
  useEffect(() => { let mounted = true; const path = section === "companies" ? "/shop/admin/b2b/companies" : section === "variants" ? "/shop/admin/b2b/variants" : section === "groups" ? "/shop/admin/b2b/customer-groups" : section === "lists" ? "/shop/admin/b2b/price-lists" : "/shop/admin/b2b/orders"; void api<unknown[]>(path).then((items) => { if (mounted) setCount(String(items.length)); }).catch(() => undefined); return () => { mounted = false; }; }, [section]);
  return count;
}

function CompaniesPanel() {
  const { t } = useTranslation();
  const [items, setItems] = useState<Company[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { try { setItems(await api<Company[]>("/shop/admin/b2b/companies")); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not load companies.")); } }
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { await api("/shop/admin/b2b/companies", { method: "POST", body: JSON.stringify({ name, ...(slug ? { slug } : {}) }) }); setName(""); setSlug(""); setMessage(t("Company created.")); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not create company.")); } finally { setSaving(false); } }
  return <><div className="b2b-toolbar"><form onSubmit={create} className="b2b-form"><div className="b2b-form-grid"><label>{t("Company name")}<input required minLength={2} value={name} onChange={(event) => setName(event.target.value)} placeholder={t("Acme Industries")} /></label><label>{t("Slug")}<input value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="acme-industries" /></label></div><button className="admin-action" disabled={saving}>{saving ? t("Creating…") : t("Create company")}</button></form></div><ErrorNotice error={error} /><SuccessNotice message={message} /><section className="content-card"><div className="section-heading"><div><p className="eyebrow">{t("Company directory")}</p><h2>{t("Business accounts")}</h2></div><span className="b2b-muted">{t("Owners and member access")}</span></div>{items.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>{t("Company")}</th><th>{t("Status")}</th><th>{t("Members")}</th><th>{t("Customer group")}</th><th>{t("Actions")}</th></tr></thead><tbody>{items.map((company) => <tr key={company.id}><td><strong>{company.name}</strong><small>{company.slug}</small></td><td><Badge value={company.status} /></td><td>{company._count?.memberships ?? company.memberships?.length ?? 0}</td><td>{company.customerGroup?.name ?? t("Not assigned")}</td><td><Link className="text-button" href={`/dashboard/shop/b2b/companies/${company.id}`}>{t("Manage members")}</Link></td></tr>)}</tbody></table></div> : !error && <B2bState title={t("No companies yet")} detail={t("Create a company to start assigning buyers and pricing rules.")} />}</section></>;
}

function VariantsPanel() {
  const { t } = useTranslation();
  const [items, setItems] = useState<Variant[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [query, setQuery] = useState(""); const [productId, setProductId] = useState(""); const [form, setForm] = useState({ sku: "", name: "", basePriceMinor: "0", stockQty: "0", minimumOrderQty: "1", packSize: "1", quantityIncrement: "1", currency: "USD" }); const [saving, setSaving] = useState(false);
  async function load() { try { setItems(await api<Variant[]>(`/shop/admin/b2b/variants${query ? `?q=${encodeURIComponent(query)}` : ""}`)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not load variants.")); } }
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { await api(`/shop/admin/b2b/products/${productId}/variants`, { method: "POST", body: JSON.stringify({ ...form, basePriceMinor: Number(form.basePriceMinor), stockQty: Number(form.stockQty), minimumOrderQty: Number(form.minimumOrderQty), packSize: Number(form.packSize), quantityIncrement: Number(form.quantityIncrement) }) }); setMessage(t("Variant created.")); setForm({ sku: "", name: "", basePriceMinor: "0", stockQty: "0", minimumOrderQty: "1", packSize: "1", quantityIncrement: "1", currency: "USD" }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not create variant.")); } finally { setSaving(false); } }
  return <><div className="b2b-toolbar"><form onSubmit={(event) => { event.preventDefault(); void load(); }}><label>{t("Search variants")}<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("SKU or product name")} /></label><button className="admin-action" type="submit">{t("Search")}</button></form></div><ErrorNotice error={error} /><SuccessNotice message={message} /><div className="management-split"><section className="content-card"><div className="section-heading"><div><p className="eyebrow">{t("New variant")}</p><h2>{t("Add sellable SKU")}</h2></div></div><form className="b2b-form" onSubmit={create}><label>{t("Product ID")}<input required value={productId} onChange={(event) => setProductId(event.target.value)} placeholder={t("Paste an existing product ID")} /></label><div className="b2b-form-grid"><label>{t("SKU")}<input required value={form.sku} onChange={(event) => setForm({ ...form, sku: event.target.value })} /></label><label>{t("Variant name")}<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>{t("Base price (minor units)")}<input min="0" type="number" value={form.basePriceMinor} onChange={(event) => setForm({ ...form, basePriceMinor: event.target.value })} /></label><label>{t("Currency")}<input maxLength={3} value={form.currency} onChange={(event) => setForm({ ...form, currency: event.target.value.toUpperCase() })} /></label><label>{t("Stock quantity")}<input min="0" type="number" value={form.stockQty} onChange={(event) => setForm({ ...form, stockQty: event.target.value })} /></label><label>{t("Minimum order") }<input min="1" type="number" value={form.minimumOrderQty} onChange={(event) => setForm({ ...form, minimumOrderQty: event.target.value })} /></label><label>{t("Pack size")}<input min="1" type="number" value={form.packSize} onChange={(event) => setForm({ ...form, packSize: event.target.value })} /></label><label>{t("Quantity increment")}<input min="1" type="number" value={form.quantityIncrement} onChange={(event) => setForm({ ...form, quantityIncrement: event.target.value })} /></label></div><button className="admin-action" disabled={saving}>{saving ? t("Creating…") : t("Create variant")}</button></form></section><section className="content-card"><div className="section-heading"><div><p className="eyebrow">{t("Catalog structure")}</p><h2>{t("Active variants")}</h2></div></div>{items.length ? <div className="management-list">{items.map((item) => <div key={item.id}><span><strong>{item.name}</strong><small>{item.product?.name ?? t("Product")} · {item.sku}</small></span><b>{formatB2bMoney(item.priceMinor ?? item.basePriceMinor ?? 0, item.currency)}<small>{item.minimumOrderQty}+ / {item.quantityIncrement}</small></b></div>)}</div> : !error && <p className="manager-note">{t("No variants match this search.")}</p>}</section></div></>;
}

function GroupsPanel() {
  const { t } = useTranslation();
  const [items, setItems] = useState<CustomerGroup[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [form, setForm] = useState({ name: "", code: "" }); const [saving, setSaving] = useState(false);
  async function load() { try { setItems(await api<CustomerGroup[]>("/shop/admin/b2b/customer-groups")); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not load customer groups.")); } }
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await api("/shop/admin/b2b/customer-groups", { method: "POST", body: JSON.stringify(form) }); setForm({ name: "", code: "" }); setMessage(t("Customer group created.")); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not create customer group.")); } finally { setSaving(false); } }
  return <><div className="management-split"><section className="content-card"><div className="section-heading"><div><p className="eyebrow">{t("Segmentation")}</p><h2>{t("Create customer group")}</h2></div></div><form className="b2b-form" onSubmit={create}><label>{t("Group name")}<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder={t("Preferred buyers")} /></label><label>{t("Group code")}<input required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} placeholder="PREFERRED" /></label><button className="admin-action" disabled={saving}>{saving ? t("Creating…") : t("Create group")}</button></form></section><section className="content-card"><div className="section-heading"><div><p className="eyebrow">{t("Pricing access")}</p><h2>{t("Customer groups")}</h2></div></div><ErrorNotice error={error} /><SuccessNotice message={message} />{items.length ? <div className="management-list">{items.map((item) => <div key={item.id}><span><strong>{item.name}</strong><small>{item.code}</small></span><b>{item._count?.companies ?? 0} {t("companies")}</b></div>)}</div> : !error && <p className="manager-note">{t("No customer groups yet.")}</p>}</section></div></>;
}

function PriceListsPanel() {
  const { t } = useTranslation();
  const [items, setItems] = useState<PriceList[]>([]); const [groups, setGroups] = useState<CustomerGroup[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [form, setForm] = useState({ name: "", code: "", currency: "USD", priority: "0", customerGroupId: "" }); const [saving, setSaving] = useState(false);
  async function load() { try { const [lists, groupItems] = await Promise.all([api<PriceList[]>("/shop/admin/b2b/price-lists"), api<CustomerGroup[]>("/shop/admin/b2b/customer-groups")]); setItems(lists); setGroups(groupItems); if (!form.customerGroupId && groupItems[0]) setForm((current) => ({ ...current, customerGroupId: groupItems[0].id })); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not load price lists.")); } }
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await api("/shop/admin/b2b/price-lists", { method: "POST", body: JSON.stringify({ ...form, priority: Number(form.priority) }) }); setMessage(t("Price list created.")); setForm((current) => ({ ...current, name: "", code: "" })); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not create price list.")); } finally { setSaving(false); } }
  return <><ErrorNotice error={error} /><SuccessNotice message={message} /><div className="management-split"><section className="content-card"><div className="section-heading"><div><p className="eyebrow">{t("Commercial rules")}</p><h2>{t("Create price list")}</h2></div></div>{groups.length ? <form className="b2b-form" onSubmit={create}><div className="b2b-form-grid"><label>{t("List name")}<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>{t("Code")}<input value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} /></label><label>{t("Currency")}<input required maxLength={3} value={form.currency} onChange={(event) => setForm({ ...form, currency: event.target.value.toUpperCase() })} /></label><label>{t("Priority")}<input type="number" value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })} /></label></div><label>{t("Customer group")}<select value={form.customerGroupId} onChange={(event) => setForm({ ...form, customerGroupId: event.target.value })}>{groups.map((group) => <option key={group.id} value={group.id}>{group.name} · {group.code}</option>)}</select></label><button className="admin-action" disabled={saving}>{saving ? t("Creating…") : t("Create price list")}</button></form> : <p className="manager-note">{t("Create a customer group before adding a price list.")}</p>}</section><section className="content-card"><div className="section-heading"><div><p className="eyebrow">{t("Effective pricing")}</p><h2>{t("Price lists")}</h2></div></div>{items.length ? <div className="management-list">{items.map((item) => <div key={item.id}><span><strong>{item.name}</strong><small>{item.code} · {item.customerGroup?.name ?? t("Customer group")} · {item.items?.length ?? 0} {t("items")}</small></span><b>{item.currency} · P{item.priority}</b></div>)}</div> : !error && <p className="manager-note">{t("No price lists yet.")}</p>}</section></div></>;
}

function OrdersPanel() {
  const { t } = useTranslation();
  const [items, setItems] = useState<B2bOrder[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { setItems(await api<B2bOrder[]>("/shop/admin/b2b/orders")); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not load B2B orders.")); } }
  useEffect(() => { void load(); }, []);
  async function update(order: B2bOrder, status: B2bOrder["status"]) { try { await api(`/shop/admin/b2b/orders/${order.id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }); setMessage(t("Order status updated.")); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not update order status.")); } }
  return <><ErrorNotice error={error} /><SuccessNotice message={message} /><section className="content-card"><div className="section-heading"><div><p className="eyebrow">{t("Fulfilment workspace")}</p><h2>{t("B2B orders")}</h2></div><span className="b2b-muted">{t("Manual payment pending")}</span></div>{items.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>{t("Order")}</th><th>{t("Company")}</th><th>{t("Requester")}</th><th>{t("Total")}</th><th>{t("Status")}</th></tr></thead><tbody>{items.map((order) => <tr key={order.id}><td><strong>{order.number}</strong><small>{new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(order.createdAt))}</small></td><td>{order.company?.name ?? "—"}</td><td>{order.createdBy?.name ?? order.createdBy?.email ?? "—"}</td><td>{formatB2bMoney(order.totalMinor, order.currency)}</td><td><select aria-label={`${t("Status")} ${order.number}`} value={order.status} onChange={(event) => void update(order, event.target.value as B2bOrder["status"])}>{(["PENDING", "PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED"] as const).map((status) => <option key={status} value={status}>{t(status)}</option>)}</select></td></tr>)}</tbody></table></div> : !error && <B2bState title={t("No B2B orders yet")} detail={t("Approved company requests will appear here for fulfilment.")} />}</section></>;
}

export function CompanyMembersPage({ companyId }: { companyId: string }) {
  const { t } = useTranslation();
  const [company, setCompany] = useState<Company | null>(null); const [members, setMembers] = useState<Membership[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [form, setForm] = useState({ email: "", role: "BUYER" as CompanyRole }); const [saving, setSaving] = useState(false);
  async function load() { try { const [details, list] = await Promise.all([api<Company>(`/shop/admin/b2b/companies/${companyId}`), api<Membership[]>(`/shop/admin/b2b/companies/${companyId}/members`)]); setCompany(details); setMembers(list); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not load company members.")); } }
  useEffect(() => { void load(); }, [companyId]);
  async function add(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await api(`/shop/admin/b2b/companies/${companyId}/members`, { method: "POST", body: JSON.stringify(form) }); setMessage(t("Member added.")); setForm({ email: "", role: "BUYER" }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not add member.")); } finally { setSaving(false); } }
  async function update(id: string, role: CompanyRole) { try { await api(`/shop/admin/b2b/companies/${companyId}/members/${id}`, { method: "PATCH", body: JSON.stringify({ role }) }); setMessage(t("Member role updated.")); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not update member.")); } }
  async function remove(id: string) { if (!window.confirm(t("Remove this member from the company?"))) return; try { await api(`/shop/admin/b2b/companies/${companyId}/members/${id}`, { method: "DELETE" }); setMessage(t("Member removed.")); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t("Could not remove member.")); } }
  return <B2bShell title={company?.name ?? "Company members"} eyebrow="Company administration" active="companies"><ErrorNotice error={error} /><SuccessNotice message={message} />{company && <div className="b2b-stat-grid"><div className="metric-card"><span>{t("Company status")}</span><strong><Badge value={company.status} /></strong></div><div className="metric-card"><span>{t("Customer group")}</span><strong>{company.customerGroup?.name ?? t("Not assigned")}</strong></div><div className="metric-card"><span>{t("Members")}</span><strong>{members.length}</strong></div></div>}<div className="management-split"><section className="content-card"><div className="section-heading"><div><p className="eyebrow">{t("Access control")}</p><h2>{t("Add member")}</h2></div></div><form className="b2b-form" onSubmit={add}><label>{t("User email")}<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>{t("Role")}<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as CompanyRole })}>{roleOptions.map((role) => <option key={role}>{role}</option>)}</select></label><button className="admin-action" disabled={saving}>{saving ? t("Adding…") : t("Add member")}</button></form></section><section className="content-card"><div className="section-heading"><div><p className="eyebrow">{t("Company members")}</p><h2>{company?.name ?? t("Members")}</h2></div><Link className="text-button" href="/dashboard/shop/b2b/companies">{t("Back to companies")}</Link></div>{members.length ? <div className="management-list">{members.map((member) => <div key={member.id}><span><strong>{member.user.name ?? member.user.email}</strong><small>{member.user.email} · <Badge value={member.status} /></small></span><span className="b2b-inline-actions"><select aria-label={`${t("Role")} ${member.user.email}`} value={member.role} onChange={(event) => void update(member.id, event.target.value as CompanyRole)}>{roleOptions.map((role) => <option key={role}>{role}</option>)}</select><button className="danger-text-button" type="button" onClick={() => void remove(member.id)}>{t("Remove")}</button></span></div>)}</div> : !error && <B2bState title={t("No members yet")} detail={t("Add a registered user to give them company access.")} />}</section></div></B2bShell>;
}
